project_id = "scuzcokginqdwdwntxfe"

[functions.pirate-chat]
verify_jwt = false

[functions.translate-text]
verify_jwt = false

[functions.speech-to-text]
verify_jwt = false

[functions.text-to-speech]
verify_jwt = false
